config/routes.rb
AlertCitizen::Application.routes.draw do
  resources :tagged_images, :only => [:index, :create]

	namespace :api do
	  namespace :v1  do
	    resources :tokens,:only => [:create, :destroy]
	  end
	end

  devise_for :users

  root :to => 'tagged_images#index'

end

app/models/tagged_image.rb
class TaggedImage < ActiveRecord::Base
	belongs_to :user
	belongs_to :theme
	acts_as_gmappable
	has_attached_file :image, :styles => {:thumbnail => "64x64#"}, 
:path => ":rails_root/public/images/:id/:style/:filename", :url => "/images/:id/:style/:filename"

	scope :in_date_range, lambda { |start_date, end_date, search|
		where(search + " created_at between ? and ?", start_date, end_date).order("created_at DESC").includes('theme')
	}

	def gmaps4rails_address
	  "#{self.street_slug}" 	
	end

	def themeImage
		theme.theme_image
	end

end

app/models/theme.rb
class Theme < ActiveRecord::Base
	def theme_image
		"/images/theme_markers/"+id.to_s+".png"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role 
	has_many :tagged_images
end

app/controllers/api/v1/tokens_controller.rb
class Api::V1::TokensController < ApplicationController
    skip_before_filter :verify_authenticity_token
    respond_to :json
    def create
      email = params[:email]
      password = params[:password]
      if request.format != :json
        render :status=>406, :json=>{:message=>"The request must be json"}
        return
       end

    if email.nil? or password.nil?
       render :status=>400,
              :json=>{:message=>"The request must contain the user email and password."}
       return
    end

    @user=User.find_by_email(email.downcase)

    if @user.nil?
      logger.info("User #{email} failed signin, user cannot be found.")
      render :status=>401, :json=>{:message=>"Invalid email or passoword."}
      return
    end

    # http://rdoc.info/github/plataformatec/devise/master/Devise/Models/TokenAuthenticatable
    @user.ensure_authentication_token!

    if not @user.valid_password?(password)
      logger.info("User #{email} failed signin, password \"#{password}\" is invalid")
      render :status=>401, :json=>{:message=>"Invalid email or password."}
    else
      render :status=>200, :json=>{:user_id => @user.id, :token=>@user.authentication_token}
    end
  end

  def destroy
    @user=User.find_by_authentication_token(params[:id])
    if @user.nil?
      logger.info("Token not found.")
      render :status=>404, :json=>{:message=>"Invalid token."}
    else
      @user.reset_authentication_token!
      render :status=>200, :json=>{:token=>params[:id]}
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tagged_images_controller.rb
class TaggedImagesController < ApplicationController
	before_filter :authenticate_user!, :only => :create
  def index
		@search = []
		if(params[:emergency] == "on")
			@search << "emergency = true"
		end
		if(params[:user_id])
			@search << "user_id = " + params[:user_id].to_s
		end
		if(params[:liked] == "on" && params[:disliked] == "on")
		elsif(params[:liked] == "on")
			@search << "tagged_images.like = true"
		elsif(params[:disliked] == "on")
			@search << "tagged_images.like = false"
		end
		if(params[:search] && params[:search][:theme_ids])
			@search << "theme_id IN ("+ params[:search][:theme_ids].join(", ") + ")"
		end
		@search << " "
		@search = @search.join(" AND ")
logger.info(@search)
		if(params[:range].nil? || params[:range][:start_date].empty?|| params[:range][:end_date].empty?) 
			@start_date = Date.today - 2.days 
			@end_date = Date.today + 1.day
		else 
			@date_string = params[:range][:start_date]
			@start_date = Date.civil(@date_string.split('/')[2].to_i,@date_string.split('/')[0].to_i, @date_string.split('/')[1].to_i) 
			@date_string = params[:range][:end_date]
			@end_date = Date.civil(@date_string.split('/')[2].to_i,@date_string.split('/')[0].to_i, @date_string.split('/')[1].to_i) 
		end
		unless(params[:user_tagged] == "on")
			respond_to do |format|
				format.html do
					@json = TaggedImage.in_date_range(@start_date, @end_date, @search).to_gmaps4rails do |image, marker|
					marker.infowindow render_to_string(:partial => "/tagged_images/marker", :locals => { :image => image})
					marker.picture({
								          :picture => "#{image.themeImage}",
								          :width   => 32,
								          :height  => 32
								         })
					marker.title   "#{image.theme}"
					marker.sidebar render_to_string(:partial => "/tagged_images/marker", :locals => { :image => image})
					marker.json({ :id => image.id, :foo => "bar" })
					end
				end
				format.json do
					@json = TaggedImage.in_date_range(@start_date, @end_date, @search)
					render :json => {:tagged_images => @json}
				end
			end
		else
			@json = current_user.tagged_images.in_date_range(@start_date, @end_date, @search).to_gmaps4rails do |image, marker|
				marker.infowindow render_to_string(:partial => "/tagged_images/marker", :locals => { :image => image})
				marker.picture({
						            :picture => "#{image.themeImage}",
						            :width   => 32,
						            :height  => 32
						           })
				marker.title   "#{image.theme}"
				marker.sidebar render_to_string(:partial => "/tagged_images/marker", :locals => { :image => image})
				marker.json({ :id => image.id, :foo => "bar" })
			end
		end
		@themes = Theme.all
  end

	def create
		logger.info(params)
		@image = TaggedImage.create(:latitude => params[:latitude], :longitude => params[:longitude], :theme => params[:theme], :street_slug => params[:street_slug], :emergency => params[:emergency], :theme_id => params[:theme_id], :like => params[:like], :image => params[:image], :user_id => params[:user_id])
		render :json => {status => 200}
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tagged_images_helper.rb
module TaggedImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= yield :head %>
  <title>AlertCitizen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_menu">
	<h3>Alert Citizen</h3>
	<ul class="hmenu">
		<%= render 'users/menu/registration_items' %>
		<%= render 'users/menu/login_items' %>
	</ul>
<div class='clear'></div>
</div>
<hr />
<%= yield %>
<%= yield :scripts %>
</body>
</html>

app/views/tagged_images/_marker.html.erb
<%if image.emergency %>
	<div class="emergency" >
<% else %>
	<div>
<% end %>
<div class="street_container">
	<p><%=image.street_slug%></p>
</div>
<div class="images_container">
	<a href='<%=image.image.url%>'><img class='image' src='<%=image.image.url(:thumbnail)%>' /></a>
	<img class='theme-icon' src='<%=image.themeImage%>' />
	<%if image.emergency %>
		<%= image_tag("emergency.jpg", :height =>'32', :class=>'emergency') %>
	<% end %>
<%if image.like %>
	<%= image_tag("thumbup.png", :height =>'32', :class=>'like') %>
<% else %>
	<%= image_tag("thumbsdown.png", :height =>'32', :class=>'like') %>
<% end %>
</div>
<div class='clear'></div>

app/views/tagged_images/index.html.erb
<div  style="text-align:center;">
	<button id="search_form_button" class="right">Search Alerts</button>
	<h4 class="clear">Showing 
	<%if (params[:user_tagged]=="on")%>
		my
	<%end%>
<% @date_format = "%A, %B %e, %Y" %>
	results from <%=@start_date.strftime(@date_format)%> to <%=@end_date.strftime(@date_format)%></h4>
</div>
<div id="search_form" class="hidden">
	<%= form_tag tagged_images_path, :method => 'get', :id => "search" do %>
		  <table>
				<tr><td>From:</td><td><input name="range[start_date]" id="date_from" size="10"/></td></tr>
				<tr><td>To:</td><td><input name="range[end_date]" id="date_to" size="10" /></td></tr>
				<%if current_user %>
			 		<tr><td><input name="user_tagged" type="checkbox" /></td><td>My alerts only</td></tr> 
				<%end%>
			 	<tr><td><input name="liked" type="checkbox" /></td><td>
	<%= image_tag("thumbup.png", :height =>'32', :class=>'like') %>Liked</td></tr> 
			 	<tr><td><input name="disliked" type="checkbox" /></td><td>
	<%= image_tag("thumbsdown.png", :height =>'32', :class=>'like') %>Disliked</td></tr> 
				<tr><td><input name="emergency" type="checkbox" /></td><td>
		<%= image_tag("emergency.jpg", :height =>'32', :class=>'emergency') %><%= "Emergency alerts only" %></td></tr>
<tr><td><br /></td></tr>
				<tr><td></td><td><u>View alerts only for</u></p></td></tr>
				<% for theme in @themes %>
					<tr><td><%= check_box_tag "search[theme_ids][]", theme.id %></td><td>
	<img class='theme-icon' src='<%=theme.theme_image%>' /><p><%= theme.title %></p></td></tr>
				<% end %>
		  </table>
		  <%= submit_tag "Search", :name => nil, :class=>'hidden' %>
		</p>
	<% end %>
</div>
<div class="clear"></div>
<div id="map_info">
	<div id='map_container'>
		<%= gmaps({"map_options" => { "type" => "SATELLITE", "center_longitude" => -72,"center_latitude" => -10, "zoom" =>3, "auto_adjust" => true, "do_clustering" => true}, "markers" => {"data" => @json, "options" => {"list_container" => "markers_list" }}}) %>
	</div>
	<div id='markers_list_container'>
			<ul id="markers_list">
		  </ul>
	</div>
	<div class="clear"></div>
</div>

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/users/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>